name: null
favicon: null
layout_spectrum: 0.17889
typography_spectrum: 0.62805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4f8ccd'
    - '#ffffeb'
    - '#ff8e00'
    - '#00c7f9'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: null
    url: null
